import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, auth } from '@clerk/nextjs'
import { ThemeProvider } from "@/components/ui/theme-provider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import getUser from "@/actions/getUser";
import AdminNavbar from "@/components/AdminNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Farmers Market Finds",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = auth();
  const userInfo = await getUser(user.userId);
  return (
    <ClerkProvider afterSignInUrl="/vendorform" afterSignUpUrl="/vendorform">
      <html lang="en" suppressHydrationWarning={true}>
        <body>
          <ThemeProvider attribute="class" defaultTheme="system">
            {
              userInfo ? (userInfo.is_admin ? <AdminNavbar /> : <Navbar />) : <Navbar />
            }
            {children}
            <Footer />
            </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
