import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from "@/components/ui/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Farmers Market Finds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignInUrl="/vendorform" afterSignUpUrl="/vendorform">
      <html lang="en" suppressHydrationWarning={true}>
        <body>
          <ThemeProvider attribute="class" defaultTheme="system">{children}</ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
